### ISSUE TITLE
problem with ember-zli on one of my hosts

### ISSUE THREAD

**Issue by JacekKac** [Nerivec/ember-zli#10]
pi@i.........~ $ ember-zli bootloader
    SyntaxError: The requested module 'zlib' does not provide an export named 'crc32'
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

npm -v
10.9.1
node -v
v20.5.1

**Comment by Nerivec** [comment]
Update to latest v20 node (>=20.15) and the problem should disappear.
https://github.com/Nerivec/ember-zli/wiki#from-npm

**Comment by JacekKac** [comment]
the install was on node 16, then i updated to 20 and need to run install command again, now it's working
